# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('telphone', models.IntegerField()),
                ('CreateTime', models.DateTimeField()),
                ('Last_LoginTime', models.DateTimeField()),
            ],
        ),
    ]
